const departmentsData = [
  {
    department: "Procurement",
    sectors: [
      "Construction",
      "IT",
      "Healthcare",
      "Energy",
      "Manufacturing",
      "Agriculture",
    ],
    productsServices: [
      "Office supplies",
      "IT systems and hardware",
      "Construction materials",
      "Engineering equipment",
      "Facility management services",
      "Pharmaceuticals",
      "Logistics services",
    ],
  },
  {
    department: "Finance",
    sectors: [
      "Financial Services",
      "Insurance",
      "Banking",
      "Investment Management",
    ],
    productsServices: [
      "Financial advisory services",
      "Accounting software",
      "Audit services",
      "Insurance products",
      "Investment portfolios",
      "Payment gateway solutions",
    ],
  },
  {
    department: "Human Resources",
    sectors: ["Healthcare", "Education", "Manufacturing", "IT", "Government"],
    productsServices: [
      "Recruitment services",
      "Training programs",
      "Employee wellness services",
      "HR software",
      "Staff management systems",
      "Employee benefits packages",
    ],
  },
  {
    department: "Information Technology",
    sectors: [
      "IT",
      "Healthcare",
      "Telecom",
      "Finance",
      "Education",
      "Public Sector",
    ],
    productsServices: [
      "Software development",
      "IT infrastructure",
      "Cloud computing",
      "Networking services",
      "Medical IT systems",
      "Data security solutions",
      "E-learning platforms",
    ],
  },
  {
    department: "Operations",
    sectors: [
      "Logistics",
      "Manufacturing",
      "Retail",
      "Construction",
      "Agriculture",
    ],
    productsServices: [
      "Logistics services",
      "Supply chain management systems",
      "Manufacturing tools and machinery",
      "Construction equipment",
      "Inventory management systems",
    ],
  },
  {
    department: "Legal",
    sectors: [
      "Legal and Compliance",
      "Finance",
      "Government",
      "Construction",
      "Healthcare",
    ],
    productsServices: [
      "Contract law services",
      "Legal consultancy",
      "Compliance auditing",
      "Risk management services",
      "Environmental law services",
      "Intellectual property management",
    ],
  },
  {
    department: "Marketing",
    sectors: ["Retail", "E-commerce", "Tourism", "Healthcare", "Entertainment"],
    productsServices: [
      "Branding services",
      "Digital marketing",
      "Advertising",
      "Public relations services",
      "Event management",
      "Market research",
      "Graphic design",
    ],
  },
  {
    department: "Construction and Engineering",
    sectors: ["Construction", "Infrastructure", "Real Estate", "Energy"],
    productsServices: [
      "Building materials",
      "Engineering services",
      "Civil engineering solutions",
      "Road and bridge construction",
      "Renewable energy systems",
      "Project management solutions",
    ],
  },
  {
    department: "Facilities Management",
    sectors: ["Real Estate", "Healthcare", "Education", "Government"],
    productsServices: [
      "Building maintenance",
      "Janitorial services",
      "Security services",
      "Waste management",
      "Energy efficiency solutions",
      "Landscaping and gardening services",
    ],
  },
  {
    department: "Research and Development",
    sectors: ["Pharmaceuticals", "Technology", "Agriculture", "Manufacturing"],
    productsServices: [
      "Product development",
      "Scientific research",
      "Prototyping",
      "Testing and quality assurance",
      "Environmental impact studies",
      "Agricultural research solutions",
    ],
  },
  {
    department: "Sales and Customer Service",
    sectors: [
      "Retail",
      "E-commerce",
      "Telecommunications",
      "Technology",
      "Logistics",
    ],
    productsServices: [
      "CRM software",
      "Call center services",
      "Lead generation",
      "Sales consultancy",
      "Customer service training",
      "Product/service promotions",
      "Subscription management",
    ],
  },
  {
    department: "Health and Safety",
    sectors: [
      "Manufacturing",
      "Construction",
      "Healthcare",
      "Energy",
      "Agriculture",
    ],
    productsServices: [
      "Personal protective equipment",
      "Safety training programs",
      "Risk management services",
      "Emergency response solutions",
      "Environmental health services",
    ],
  },
  {
    department: "Supply Chain and Logistics",
    sectors: ["Retail", "Manufacturing", "Agriculture", "Logistics", "Energy"],
    productsServices: [
      "Freight services",
      "Warehousing",
      "Inventory management systems",
      "Packaging and distribution",
      "Last-mile delivery services",
      "Cold chain solutions",
    ],
  },
  {
    department: "Public Relations",
    sectors: ["Retail", "Tourism", "Entertainment", "Healthcare", "Government"],
    productsServices: [
      "Press releases",
      "Media relations",
      "Crisis management",
      "Public campaigns",
      "Community outreach programs",
      "Event promotions",
      "Social media engagement",
    ],
  },
  {
    department: "Environmental and Sustainability",
    sectors: [
      "Renewable Energy",
      "Agriculture",
      "Manufacturing",
      "Construction",
    ],
    productsServices: [
      "Renewable energy solutions",
      "Waste management systems",
      "Green construction solutions",
      "Carbon footprint assessment",
      "Eco-friendly products",
      "Water and waste treatment",
    ],
  },
  {
    department: "Executive or Leadership Team",
    sectors: [
      "Corporate Development",
      "Government",
      "Business Strategy",
      "Public Sector",
    ],
    productsServices: [
      "Business strategy development",
      "Corporate governance services",
      "Public sector consulting",
      "CSR initiatives",
      "Mergers and acquisitions consulting",
    ],
  },
  {
    department: "Government or Public Sector",
    sectors: [
      "Public Services",
      "Infrastructure",
      "Education",
      "Healthcare",
      "Energy",
      "Construction",
    ],
    productsServices: [
      "Public works contracts",
      "Government building and infrastructure projects",
      "Public healthcare services",
      "Social welfare programs",
      "Policy and strategy development",
    ],
  },
];

export default departmentsData;
