import { Supplier } from "../../types/type";

export const dummySuppliers: Supplier[] = [
  {
    companyName: "Acme Supplies Ltd.",
    registeredAddress: "123 Industrial Park, Sector 45",
    postalAddress: "PO Box 789",
    phoneNumber: "+1-555-123-4567",
    email: "contact@acmesupplies.com",
    websiteURL: "https://www.acmesupplies.com",
    registrationNumber: "REG-2025-001",
    vatNumber: "VAT1234567",
    contactName: "John Doe",
    contactPosition: "Procurement Manager",
    contactPhoneNumber: "+1-555-987-6543",
    contactEmail: "johndoe@acmesupplies.com",
    industry: "Manufacturing",
    supplierType: "Raw Materials",
    keyProducts: "Steel, Aluminum, Copper",
    yearsOfExperience: 15,
    certifications: "ISO 9001, ISO 14001",
    insuranceCoverage: "Comprehensive Liability",
    annualTurnover: "$5,000,000",
    creditRating: "A+",
    bankAccount: "1234567890",
    taxCompliant: "Yes",
    prevTenders: "Tender-001, Tender-002",
    relevantProjects: "Project A, Project B",
    references: "Client X, Client Y",
    legalStructure: "Private Limited",
    regulations: "Compliant with industry standards",
    conflicts: "None",
    nda: "Signed",
    criminal: "None",
    qualityManagement: "Implemented",
    serviceGurantee: "1-year warranty",
    sla: "99% uptime",
    bidAmount: "$50,000",
    proposedDelivery: "30 days",
    proposedPaymentTerms: "Net 30",
    additionalInfo: "Reliable supplier with long-term experience",
    profileFile: null,
    financialStatementFile: null,
    supplierDeclaration: "I hereby declare...",
    authorizedSignatoryName: "John Doe",
    signature: null,
    date: "2025-10-08",
  },
  {
    companyName: "Global Tech Supplies",
    registeredAddress: "456 Tech Avenue, Silicon Valley",
    postalAddress: "PO Box 456",
    phoneNumber: "+1-555-234-5678",
    email: "info@globaltech.com",
    websiteURL: "https://www.globaltech.com",
    registrationNumber: "REG-2025-002",
    vatNumber: "VAT2345678",
    contactName: "Alice Smith",
    contactPosition: "Head of Procurement",
    contactPhoneNumber: "+1-555-876-5432",
    contactEmail: "alice.smith@globaltech.com",
    industry: "Electronics",
    supplierType: "Components",
    keyProducts: "Semiconductors, Sensors, Circuit Boards",
    yearsOfExperience: 10,
    certifications: "ISO 9001, ISO 27001",
    insuranceCoverage: "Comprehensive Liability",
    annualTurnover: "$8,500,000",
    creditRating: "A",
    bankAccount: "2345678901",
    taxCompliant: "Yes",
    prevTenders: "Tender-003, Tender-004",
    relevantProjects: "Project C, Project D",
    references: "Client Z, Client W",
    legalStructure: "Private Limited",
    regulations: "Compliant with electronics standards",
    conflicts: "None",
    nda: "Signed",
    criminal: "None",
    qualityManagement: "Implemented",
    serviceGurantee: "2-year warranty",
    sla: "98% uptime",
    bidAmount: "$75,000",
    proposedDelivery: "45 days",
    proposedPaymentTerms: "Net 45",
    additionalInfo: "Trusted supplier in tech industry",
    profileFile: null,
    financialStatementFile: null,
    supplierDeclaration: "I hereby declare...",
    authorizedSignatoryName: "Alice Smith",
    signature: null,
    date: "2025-10-08",
  },
  {
    companyName: "Prime Materials Co.",
    registeredAddress: "789 Industrial Lane, Sector 12",
    postalAddress: "PO Box 123",
    phoneNumber: "+1-555-345-6789",
    email: "sales@primematerials.com",
    websiteURL: "https://www.primematerials.com",
    registrationNumber: "REG-2025-003",
    vatNumber: "VAT3456789",
    contactName: "Robert Johnson",
    contactPosition: "Supply Chain Manager",
    contactPhoneNumber: "+1-555-765-4321",
    contactEmail: "robert.johnson@primematerials.com",
    industry: "Construction",
    supplierType: "Building Materials",
    keyProducts: "Cement, Bricks, Timber",
    yearsOfExperience: 20,
    certifications: "ISO 9001, ISO 45001",
    insuranceCoverage: "Comprehensive Liability",
    annualTurnover: "$12,000,000",
    creditRating: "AA",
    bankAccount: "3456789012",
    taxCompliant: "Yes",
    prevTenders: "Tender-005, Tender-006",
    relevantProjects: "Project E, Project F",
    references: "Client M, Client N",
    legalStructure: "Private Limited",
    regulations: "Compliant with construction standards",
    conflicts: "None",
    nda: "Signed",
    criminal: "None",
    qualityManagement: "Implemented",
    serviceGurantee: "3-year warranty",
    sla: "97% uptime",
    bidAmount: "$120,000",
    proposedDelivery: "60 days",
    proposedPaymentTerms: "Net 60",
    additionalInfo: "Experienced supplier for large-scale construction",
    profileFile: null,
    financialStatementFile: null,
    supplierDeclaration: "I hereby declare...",
    authorizedSignatoryName: "Robert Johnson",
    signature: null,
    date: "2025-10-08",
  },
];
