import { z } from "zod";

export const supplierSchema = z.object({
  companyName: z.string().min(1, "Company Name is required"),
  registeredAddress: z.string().min(1, "Registered Address is required"),
  postalAddress: z.string().optional(),
  phoneNumber: z.string().min(1, "Phone Number is required"),
  email: z.string().email("Invalid email address"),
  websiteURL: z.string().optional(),
  registrationNumber: z.string().optional(),
  vatNumber: z.string().optional(),
  contactName: z.string().optional(),
  contactPosition: z.string().optional(),
  contactPhoneNumber: z.string().optional(),
  contactEmail: z.string().optional(),
  industry: z.string().optional(),
  supplierType: z.enum(["Manufacturer", "Distributor", "Service Provider"]).optional(),
  yearsOfExperience: z.string().optional(),
  keyProducts: z.string().optional(),
  certifications: z.any().optional(),
  insuranceCoverage: z.string().optional(),
  prevTenders: z.string().optional(),
  relevantProjects: z.string().optional(),
  references: z.any().optional(),
  annualTurnover: z.string().optional(),
  creditRating: z.string().optional(),
  bankAccount: z.string().optional(),
  taxCompliant: z.enum(["Yes", "No"]).optional(),
  legalStructure: z.enum(["Sole Partnership", "Limited Liability Company", "Corporation"]).optional(),
  regulations: z.array(z.string()).optional(),
  conflicts: z.string().optional(),
  nda: z.string().optional(),
  criminal: z.string().optional(),
  qualityManagement: z.string().optional(),
  serviceGurantee: z.string().optional(),
  sla: z.any().optional(),
  bidAmount: z.string().optional(),
  proposedDelivery: z.string().optional(),
  proposedPaymentTerms: z.string().optional(),
  additionalInfo: z.string().optional(),
  profileFile: z.any().optional(),
  financialStatementFile: z.any().optional(),
  supplierDeclaration: z.string().optional(),
  authorizedSignatoryName: z.string().optional(),
  signature: z.any().optional(),
  date: z.string().optional(),
});

export type SupplierFormType = z.infer<typeof supplierSchema>;
